# Soc5044 Computational Sociology W2 Practicum - Python Basic Part 2

These teaching materials are adpated from [*Introduction to Cultural Analytics & Python*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/welcome.html) (Walsh 2021) for the course "Soc5044 Computational Sociology" lectured at the sociology department of National Taiwan University by Dr. Chen-Shuo Hong.

In particular, this file uses the following chapters:
- "Python Comparisons and Conditionals", Chapter 2 Python Basics.
- "Python Lists and Loops", Chapter 2 Python Basics.
- "Python Lists and Loops (Cont.)", Chapter 2 Python Basics.
- "Python Dictionaries", Chapter 2 Python Basics.

> Melanie Walsh, Introduction to Cultural Analytics & Python, Version 1 (2021), https://doi.org/10.5281/zenodo.4411250.

Editor: Jun-Wei Liu (b09902009@ntu.edu.tw)

---

# 1. Comparisons & Conditionals

Writing Python code is a lot like writing a list of detailed instructions to the computer. Most of the time you will be asking the computer to perform certain tasks if certain conditions are met. For example:

- *If a person in the dataset is older than 30, then print out their name*
- *If a tweet contains the phrase "ok boomer," then automatically retweet it*
- *If Beyoncé is a Grammy award-winner, then say "Congratulations, Beyoncé!*

Here's how we would write out this last example in Python code:

In [ ]:
beyonce = "Grammy award-winner"

In [ ]:
if beyonce == "Grammy award-winner":
    print("Congratulations, Beyonce!")

Congratulations, Beyonce!

There are two important Python elements present in the code above: a *comparison* and a *conditional*. We compared whether the variable `beyonce` is equal to the value `"Grammy award-winner"`. Then we printed "Congratulations" if this condition was `True`.

## Comparisons

There are many ways that we can compare values with Python, such as equals (`==`), not equals (`!=`), greater than (`>`), less than (`<`), greater than or equal to (`>=`), or less than or equal to (`<=`).

| **Comparison Operator** | **Explanation**                                                                                   |
|:-------------:|:---------------------------------------------------------------------------------------------------:|
| `x == y `         | `True` if x is equal to y                                                                                |
| `x != y `         | `True` if x is not equal to y                                               |
| `x > y`       |  `True` if x is greater than y                                                        |
| `x < y`       |   `True` if x is less than y  
| `x >= y`       |   `True` if x is greater than or equal to y |
| `x <= y`      | `True` if x is less than or equal to y`                                                                             |

### Greater Than

Is the variable `person1` greater than `person1`?

In [ ]:
person1 = 30
person2 = 30.5
person1 > person2

False

### Not Equals

Is the variable `person1` not equal to `person1`?

In [ ]:
person1 = 30
person2 = 30.5
person1 != person2

True

We can also combine values and compare them. We can check to see if `x and y` are both `True` or if either `x or y` is `True`.

| **Logical Operator** | **Explanation**                                                                                   |
|:-------------:|:---------------------------------------------------------------------------------------------------:|
| `x and y`         | `True` if x and y are both True                                                                             |
| `x or y`         | `True` if either x or y is True                                              |
| `not x`       |  `True` if is x is not True                                                       |

### And

What will happen if we check whether `person1 > 30` and `person2 > 30`?

In [ ]:
person1 = 30
person2 = 30.5
person1 > 30 and person2 > 30

False

The boolean answer is `False` because `person1` is not greater than 30 (`person1` is exactly 30) even though `person2` is greater than 30. The `and` requires that both conditions are `True.`

In [ ]:
person1 = 30
person2 = 30.5
person1 >= 30 and person2 >= 30

True

The boolean answer is `True` because `person1` is greater than or equal to 30 and `person2` is greater or equal to  30. The `and` requires that both conditions are `True.`

### Or

What will happen if we check whether `person1 > 30` or `person2 > 30`?

In [ ]:
person1 = 30
person2 = 30.5
person1 > 30 or person2 > 30

True

The boolean answer is `True` because `person2` is greater than 30. The `or` requires that only one of the conditions is true.

## Conditionals

### If Statement

An `if` statement is an instruction to do something *if* a particular condition is met.

A common conditional will consist of two lines: 
- On the first line, you type the English word `if` followed by an expression and then a colon (`:`) 
- On the second line, you indent and write an instruction or "statement" to be completed if the condition is met

In [ ]:
beyonce = "Grammy award-winner"

In [ ]:
if beyonce == "Grammy award-winner":
    print("Congratulations, Beyonce!")

Congratulations, Beyonce!

Python is picky about how you format `if` statements. Look what happens if we forget to tab over on the second line or if we forget the colon:

In [ ]:
if beyonce == "Grammy award-winner":
print("Congratulations, Beyonce!")

IndentationError: expected an indented block (<ipython-input-26-d73728e9035a>, line 2)

In [ ]:
if beyonce == "Grammy award-winner"
    print("Congratulations, Beyonce!")

SyntaxError: invalid syntax (<ipython-input-38-4a91584b2aab>, line 1)

## Else Statement

You can add even more complexity in a conditional by adding an `else` statement. This will instruct the program to do something in case the condition is not met. An `else` comes after an `if` statement and should be formatted it the same way.

In [ ]:
beyonce = "not a Grammy award-winner this year"

In [ ]:
if beyonce == "Grammy award-winner":
    print("Congratulations, Beyonce!")
else:
    print("They messed up, Beyonce.")

They messed up, Beyonce.

## Elif Statement

Sometimes you want even more nuance to respond to slightly different conditions. For example, if Beyonce was nominated for a Grammy but didn't win, then we might want to express a slightly different sentiment than if she won or was not nominated at all.

You can add in this nuance with an `elif` statement, short for *else if*. The computer will evaluate the first `if` statement. If that statement is not `True`, it will then evaluate the `elif` statement.

In [ ]:
beyonce = "Grammy award-nominee"

In [ ]:
if beyonce == "Grammy award-winner":
    print("Congratulations, Beyonce!")
elif beyonce == "Grammy award-nominee":
    print("Ok well at least they nominated you, Beyonce.")
else:
    print("They messed up, Beyonce.")

Ok well at least they nominated you, Beyonce.

## Excerises

For the following exercises and the next few lessons, we're going to draw on Anelise Shrout's [Bellevue Almshouse Dataset](https://www.nyuirish.net/almshouse/the-almshouse-records/). The Bellevue Almshouse Dataset includes information about Irish-born immigrants who were admitted to the almshouse in the 1840s.

The Bellevue Almshouse was part of New York City's public health system, a place where poor, sick, homeless, and otherwise marginalized people were sent — sometimes voluntarily and sometimes forcibly. Devastated by widespread famine in Ireland, many Irish people fled their homes for New York City in the 1840s, and many of them ended up in the Bellevue Almshouse. This dataset was transcribed from the almshouse's own admissions records.

In [ ]:
import pandas
pandas.read_csv("../data/bellevue_almshouse_modified.csv").head(20)

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,f,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo
5,1847-04-14,Bridget,Hart,20.0,recent emigrant,spinster,f,Child
6,1847-04-14,Mary,Green,40.0,recent emigrant,spinster,f,And child 2 months
7,1847-04-19,Daniel,Loftus,27.0,destitution,laborer,m,NaN
8,1847-04-10,James,Day,35.0,recent emigrant,laborer,m,NaN
9,1847-04-10,Margaret,Farrell,30.0,recent emigrant,widow,f,NaN
10,1847-04-10,Bridget,Day,30.0,recent emigrant,married,f,NaN
11,1847-04-10,Anthony,Day,0.5,recent emigrant,NaN,m,NaN
12,1847-04-07,James,Collins,22.0,recent emigrant,laborer,m,NaN
13,1847-04-07,Thomas,Collins,21.0,recent emigrant,laborer,m,NaN
14,1847-04-07,Pat,Whalen,25.0,recent emigrant,laborer,m,NaN
15,1847-04-17,Dan,Delany,10.0,typhus,NaN,m,NaN
16,1847-04-09,Catherine,O'Harra,23.0,recent emigrant,married,f,NaN
17,1847-04-09,Damiel,O'Harra,25.0,recent emigrant,laborer,m,NaN
18,1847-04-12,Margaret,Delaney,26.0,recent emigrant,married,f,NaN
19,1847-04-12,Michael,Delany,3.0,recent emigrant,NaN,m,NaN

We're using the Bellevue Almshouse Dataset to practice `if`, `elif`, and `else` statements because we want to think deeply about the consequences of reducing human life to data and evaluating "Truth" in Pythonic terms even at this early stage in our Python journey.

As Shrout argues in her essay ["(Re)Humanizing Data: Digitally Navigating the Bellevue Almshouse,"](https://crdh.rrchnm.org/essays/v01-10-(re)-humanizing-data/) "Nineteenth-century immigration data was produced with the express purpose of reducing people to bodies; bodies to easily quantifiable aspects; and assigning value to those aspects which proved that the marginalized people to who they belonged were worth less than their elite counterparts."

As you complete the exercises below, reflect about the categories that these Irish immigrants were slotted into by the government. For example, the so-called "disease" that many of the people in this dataset exhibited — the reason they were admitted to the Almshouse in the first place — is "recent emigrant." What does this uncomfortable fact tell us about data more broadly? What should we make of the fact that Python, as a programming language, doesn't understand the meaning or historical context of this data?

### Exercise 1

In [ ]:
person1_name = 'Mary Gallagher'
person1_age = 28
person1_disease = 'recent emigrant'
person1_profession = 'married'
person1_gender = 'f'
person1_child_status = 'Child Alana 10 days'

Write an `if` statement that reports whether `person1_age` is less than 30 years old

In [ ]:
#Your code here
    print('Person is less than 30 years old.')

Person is less than 30 years old.

### Exercise 2
Write an `if` statement that reports whether `person1_profession` is "married"

In [ ]:
#Your code here
    print('Person is married.')

Person is married.

### Exercise 3
Write an `if` statement that reports whether `person1_age` is less than 30 years old *and* `person1_profession` is "married"

In [ ]:
#Your code here
    print('Person is less than 30 years old and married.')

Person is less than 30 years old and married.

### Exercise 4

In [ ]:
person2_name = 'Anthony Clark'
person2_age = 60
person2_disease = 'recent emigrant'
person2_profession = 'laborer'
person2_gender = 'm'
person2_child_status = 'Charles Riley afed 10 days'

Combine an`if` statement with an `else` statement that will report whether `person2_age` is less than 30 years old or, if not, more than 30 years old

In [ ]:
#Your code here
    print('Person is less than 30 years old.')
#Your code here
    print('Person is more than 30 years old.')

Person is more than 30 years old.

### Exercise 5

In [ ]:
person3_name = 'Margaret Farrell'
person3_age = 30
person3_disease = 'recent emigrant'
person3_profession = 'widow'
person3_gender = 'w'
person3_child_status = ''

Add an `elif` statement that reports whether `person3_age` is exactly 30 years old

In [ ]:
#Your code here
    print('Person is less than 30 years old.')
#Your code here
    print('Person is exactly 30 years old.')
#Your code here
    print('Person is more than 30 years old.')

Person is exactly 30 years old.

### Exercise 6

In [ ]:
person1_child_status = 'Child Alana 10 days'
person3_child_status = ''

Write an `if` statement that will report whether `person1_child_status` includes children

In [ ]:
#Your code here
    print('Person has children.')

Person has children.

### Exercise 7
Write a single `if` statement that will accurately report whether `person1_child_status` includes children and if `person3_child_status` includes children

```{hint}
:class: dropdown
Think about how you might use the `!=` operator!  

And remember that there's a difference between quotation marks with no space `''` and quotation marks with a space`' '`. Python is picky!
```

In [ ]:
if person1_child_status #Your Code Here
    print('Person has children.')

In [ ]:
if person2_child_status #Same Code Here
    print('Person has children.')

### Excerise 8

In [ ]:
person1_profession = 'married'

Write a conditional that will report whether `person1_profession` is "married," "laborer," "widow," or "unknown profession." Then test your code by reassigning the variable as indicated below.

In [ ]:
#Your code here
    print('Person is married.')
#Your code here
    print('Person is a laborer.')
#Your code here
    print('Person is a widow.')
#Your code here
    print('Person has unknown profession.')

Person is married.

In [ ]:
person1_profession = 'laborer'

In [ ]:
#Your code here
    print('Person is married.')
#Your code here
    print('Person is a laborer.')
#Your code here
    print('Person is a widow.')
#Your code here
    print('Person has unknown profession.')

Person is a laborer.

In [ ]:
person1_profession = 'student'

In [ ]:
#Your code here
    print('Person is married.')
#Your code here
    print('Person is a laborer.')
#Your code here
    print('Person is a widow.')
#Your code here
    print('Person has unknown profession.')

Person has unknown profession.

### Exercise 9

In [ ]:
person4_name = 'John Sanin(?)'


Some of the Irish immigrants' names have question marks after them. Let's clean up some of the data and remove the question marks.

You can use the Python keyword `in` to test whether a string appears within another string. Print `person4_name` with the question mark and parentheses removed. 
```{hint}
:class: dropdown
Remember the string method `.replace()`?

In [ ]:
if "(?)" in person2_name:
    #Your code here

John Sanin

### Exercise 10
In a few sentences, discuss the following dilemma. Python doesn't understand the historical context or human meaning behind data. What consequences might this incomprehension have on our society? How can we be sure to preserve the historical context and human meaning behind data when we are working with Python?

**Double-click this cell to type your thoughts here**

# 2. Lists & Loops — Part 1

*Note: You can explore the [associated workbook](https://mybinder.org/v2/gh/melaniewalsh/Intro-Cultural-Analytics/master?urlpath=lab/tree/book/02-Python/Workbooks/09.5-Lists-Loops-Part1-WORKBOOK.ipynb) for this chapter in the cloud.*

In the next few lessons, we're going to learn about a Python data collection type called a *list* and a way of working with lists called a *for loop*, and we're going to draw on [The Bellevue Almshouse Dataset](https://www.nyuirish.net/almshouse/the-almshouse-records/), created by historian and DH scholar Anelise Shrout. This dataset includes information about Irish-born immigrants who were admitted to New York City's Bellevue Almshouse in the 1840s.

**Preview The Bellevue Almshouse Dataset**

In [1]:
import pandas
pandas.read_csv("../data/bellevue_almshouse_modified.csv").head(20)

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo
5,1847-04-14,Bridget,Hart,20.0,recent emigrant,spinster,w,Child
6,1847-04-14,Mary,Green,40.0,recent emigrant,spinster,w,And child 2 months
7,1847-04-19,Daniel,Loftus,27.0,destitution,laborer,m,NaN
8,1847-04-10,James,Day,35.0,recent emigrant,laborer,m,NaN
9,1847-04-10,Margaret,Farrell,30.0,recent emigrant,widow,w,NaN
10,1847-04-10,Bridget,Day,30.0,recent emigrant,married,w,NaN
11,1847-04-10,Anthony,Day,0.5,recent emigrant,NaN,m,NaN
12,1847-04-07,James,Collins,22.0,recent emigrant,laborer,m,NaN
13,1847-04-07,Thomas,Collins,21.0,recent emigrant,laborer,m,NaN
14,1847-04-07,Pat,Whalen,25.0,recent emigrant,laborer,m,NaN
15,1847-04-17,Dan,Delany,10.0,typhus,NaN,m,NaN
16,1847-04-09,Catherine,O'Harra,23.0,recent emigrant,married,w,NaN
17,1847-04-09,Damiel,O'Harra,25.0,recent emigrant,laborer,m,NaN
18,1847-04-12,Margaret,Delaney,26.0,recent emigrant,married,w,NaN
19,1847-04-12,Michael,Delany,3.0,recent emigrant,NaN,m,NaN

```{margin} The Bellevue Almshouse Dataset 
The Bellevue Almshouse Dataset includes information about Irish-born immigrants who were admitted to the almshouse in the 1840s. The Bellevue Almshouse was part of New York City's public health system, a place where poor, sick, homeless, and otherwise marginalized people were sent — sometimes voluntarily and sometimes forcibly. This dataset was transcribed from the almshouse's own admissions records by Anelise Shrout.
```

We're using the [Bellevue Almshouse](https://www.nyuirish.net/almshouse/the-almshouse-records/) data to practice lists and loops because we want to think deeply about the consequences of reducing human life to data, even at this early stage in our Python journey. This immigration data, as Shrout argues in her essay ["(Re)Humanizing Data: Digitally Navigating the Bellevue Almshouse,"](https://crdh.rrchnm.org/essays/v01-10-(re)-humanizing-data/) was "produced with the express purpose of reducing people to bodies; bodies to easily quantifiable aspects; and assigning value to those aspects which proved that the marginalized people to who they belonged were worth less than their elite counterparts."

As we work through the lesson below, reflect about the categories that these Irish immigrants were slotted into by the NYC government. What should we make of the fact that Python, as a programming language, doesn't understand the meaning or historical context of this data? How can we nevertheless use Python to better understand this history and to interrogate power?

___

## Lists

In the previous lesson, we used individual variables to represent some of the demographic information about the 19th century Irish immigrants featured in the  [Bellevue Almshouse data](https://docs.google.com/spreadsheets/d/1uf8uaqicknrn0a6STWrVfVMScQQMtzYf5I_QyhB9r7I/edit##gid=2057113261), such as names.

In [ ]:
person1_name = 'Marry Gallagher'
person2_name = 'John Sanin (?)'

It's typically more useful, however, to create a *collection* of values rather than individual variables.

One of the most common Python data collections is a *list*. By using a list, we can put the names of the people featured in the dataset into a single collection.

In [ ]:
names = ['Mary Gallagher', 'John Sanin(?)', 'Anthony Clark', 'Margaret Farrell']

In [ ]:
type(names)

list

A list is always enclosed by square brackets `[]` and accepts items in a row separated by commas (`,`). A list can contain any combination of Python data types.

In [ ]:
ages = [28, 19, 60, 30]

In [ ]:
type(ages)

list

### Index

You can index a list like you would index a string.

In [ ]:
names = ['Mary Gallagher', 'John Sanin(?)', 'Anthony Clark', 'Margaret Farrell']

For example, if we wanted to pull out the first item in our `names` list, we could put square brackets and our desired index number immediately after the list. Just like with strings, the Python index begins with 0.

In [ ]:
names[0]

'Mary Gallagher'

In [ ]:
names[3]

'Margaret Farrell'

You can also reverse index a list.

In [ ]:
names[-1]

'Margaret Farrell'

### Slice

You can also slice lists like you can slice a string.

In [ ]:
more_names = ['Unity', 'Catherine', 'Thomas', 'William', 'Patrick',
              'Mary Anne', 'Morris', 'Michael', 'Ellen', 'James']

The full notation and options for slicing a list are as follows:

In [ ]:
your_list[start:stop:step]

By putting specific index numbers between these colons, you can slice the list at certain starting and stopping points, and you can also "step" by different amounts—that is, you can jump by a certain number through the list and only take every nth item in the list (e.g. every 3rd item).

````{list-table}
:header-rows: 1

* - Slice 
  - Explanation
  - Output
* - ```
     more_names[:2]
     ```
  - Slice list up to 2nd item
  - ```
    ['Unity', 'Catherine']
    ```
* - ```
     more_names[2:]
     ```
  - Slice from 2nd item to end of list 
  - ```
      ['Thomas',
     'William',
     'Patrick',
     'Mary Anne',
     'Morris',
     'Michael',
     'Ellen',
     'James']
    ```
* - ```
     more_names[::3]
     ```
  - Slice from 0 to end of list, stepping by 3
  - ```
    ['Unity', 'William', 'Morris', 'James']
    ```

````

#### Start

In [ ]:
more_names = ['Unity', 'Catherine', 'Thomas', 'William', 'Patrick',
              'Mary Anne', 'Morris', 'Michael', 'Ellen', 'James']

Here's how we would slice the list starting from the 2nd item of the list until the end.

In [ ]:
more_names[2:]

['Thomas',
 'William',
 'Patrick',
 'Mary Anne',
 'Morris',
 'Michael',
 'Ellen',
 'James']

You might imagine the above as:

In [ ]:
more_names[start=2:stop=none:step=none]

Remember that the Python index starts with `0` so the 2nd item is really the 3rd item.

In [ ]:
more_names[2]

'Thomas'

#### Reverse

In [ ]:
more_names = ['Unity', 'Catherine', 'Thomas', 'William', 'Patrick',
              'Mary Anne', 'Morris', 'Michael', 'Ellen', 'James']

Because we can reverse index a list from the end to the beginning, we can also slice a list by starting from the 2nd to last item until the end.

In [ ]:
more_names[-2:]

['Ellen', 'James']

You might imagine the above as:

In [ ]:
more_names[start=-2:stop=none:step=none]

#### Stop

In [ ]:
more_names = ['Unity', 'Catherine', 'Thomas', 'William', 'Patrick',
              'Mary Anne', 'Morris', 'Michael', 'Ellen', 'James']

Here's how we would slice the list starting from 0 and ending at the 2nd item in the list.

In [ ]:
more_names[:2]

['Unity', 'Catherine']

You might imagine the above as:

In [ ]:
more_names[start=0:stop=2:step=none]

#### Step

You can also index by a certain number of steps.

Here's how we could index every third item in the list.

In [ ]:
more_names[::3]

['Unity', 'William', 'Morris', 'James']

You might imagine the above as:

In [ ]:
more_names[start=0:stop=0:step=3]

## List Methods

Lists also have a number of special methods that can be used with them, such as a method for adding items to a list.

| **List Method** | **Explanation**                                                                                   |
|-------------|---------------------------------------------------------------------------------------------------|
| `list.append(another_item)`          | adds new item to end of list                                                                                |
| `list.extend(another_list)`        | adds items from another_list to list                                                |
| `list.remove(item)`        | removes first instance of item                                                       |
| `list.sort(reverse=False)`       | sort the order of list                                                                                 |                                                     |
| `list.reverse()`       | reverses order of list                                                                                 |                                                     |

### Add Items To List

| **List Method** | **Explanation**                                                                                   |
|-------------|---------------------------------------------------------------------------------------------------|
| `list.append(another_item)`          | adds new item to end of list

In [ ]:
names = ['Mary Gallagher', 'John Sanin(?)', 'Anthony Clark', 'Margaret Farrell']

In [ ]:
names.append("Lawrence Feeney")

In [ ]:
names

['Mary Gallagher',
 'John Sanin(?)',
 'Anthony Clark',
 'Margaret Farrell',
 'Lawrence Feeney']

### Sort List

| **List Method** | **Explanation**                                                                                   |
|-------------|---------------------------------------------------------------------------------------------------|
| `list.sort(reverse=False)`       | sort the order of list

In [ ]:
names.sort()

In [ ]:
names

['Anthony Clark',
 'John Sanin(?)',
 'Lawrence Feeney',
 'Margaret Farrell',
 'Mary Gallagher']

In [ ]:
ages.sort()

In [ ]:
ages

[19, 28, 30, 60]

In [ ]:
ages.sort(reverse=True)

In [ ]:
ages

[60, 30, 28, 19]

### Extend List With Another List

| **List Method** | **Explanation**                                                                                   |
|-------------|---------------------------------------------------------------------------------------------------|
| `list.extend(another_list)`        | adds items from another_list to list

In [ ]:
names.extend(ages)

In [ ]:
names

['Anthony Clark',
 'John Sanin(?)',
 'Lawrence Feeney',
 'Margaret Farrell',
 'Mary Gallagher',
 60,
 30,
 28,
 19]

## For Loops

One of the best ways to work with a list is with `for` loops. This is a way of considering each item in the list or "iterating" through the list.

In [ ]:
names = ['Mary Gallagher', 'John Sanin(?)', 'Anthony Clark', 'Margaret Farrell']

In [ ]:
for name in names:
    print(name)

Mary Gallagher
John Sanin(?)
Anthony Clark
Margaret Farrell

A basic basic `for` loop will consist of two lines:

- On the first line, you type the English word `for`, a new variable name for each item in the list, the English word `in`, the name of the list, and a colon (`:`)

- On the second line, you indent and write an instruction or “statement” to be completed for each item in the list

In [ ]:
for name in names:
    print(f"Person's name is {name}")

Person's name is Mary Gallagher
Person's name is John Sanin(?)
Person's name is Anthony Clark
Person's name is Margaret Farrell

In [ ]:
for x in names:
    print(f"Person's name is {x}")

Person's name is Mary Gallagher
Person's name is John Sanin(?)
Person's name is Anthony Clark
Person's name is Margaret Farrell

In [ ]:
ages = [28, 19, 60, 30]

In [ ]:
for age in ages:
    if age > 30:
        print("Person is less than 30 years old")
    else:
        print("Person is more than 30 years old")

Person is more than 30 years old
Person is more than 30 years old
Person is less than 30 years old
Person is more than 30 years old

In [ ]:
for age in ages:
    print(age * 2)

56
38
120
60

## Exercises

In [ ]:
professions = ['married', 'laborer', 'widow', 'laborer', ]
child_status = ['Child Alana 10 days', 'Catherine 2 mos', '', 'Charles Riley afed 10 days' ]
gender = ['f', 'm', 'w', 'm']

### Exercise 1
Extract the second item in the list `professions`.

```{hint}
:class: dropdown
Remember that the Python index begins with 0!
```

In [ ]:
##Your Code Here

'laborer'

### Exercise 2
Add the item "spinster" to your `professions` list, then print the list.

In [ ]:
##Your Code Here

In [ ]:
##Your Code Here

['married', 'laborer', 'widow', 'laborer', 'spinster']

### Exercise 3
Make a `for` loop that considers each item in the `professions` list and prints "Person's profession is ___"

In [ ]:
##Your Code Here
    ##Your Code Here

Person's profession is married
Person's profession is laborer
Person's profession is widow
Person's profession is laborer
Person's profession is spinster

### Exercise 4
Extract the fourth item in the `child_status` list.

In [ ]:
##Your Code Here

'Charles Riley afed 10 days'

### Exercise 5
Make a `for` loop that considers each item in the `child_status` list and prints "Person has child" if the person has a child and "Person does not have child" if not

In [ ]:
##Your Code Here
  ##Your Code Here
       ##Your Code Here
    ##Your Code Here
        ##Your Code Here

Person has child
Person has child
Person does not have child
Person has child

### Exercise 6
Add an item to the list `gender` called "not known"

In [ ]:
##Your Code Here

### Exercise 7
Make a `for` loop that considers each item in the `gender` list and prints "Person is male" if the person is male, "Person is female" if the person is female, and "Person's gender is not known" if unknown

In [ ]:
 ##Your Code Here
     ##Your Code Here
         ##Your Code Here
     ##Your Code Here
         ##Your Code Here
     ##Your Code Here
         ##Your Code Here

Person is female
Person is male
Person is male
Person's gender is not known

# 3. Lists & Loops — Part 2

*Note: You can explore the [associated workbook](https://mybinder.org/v2/gh/melaniewalsh/Intro-Cultural-Analytics/master?urlpath=lab/tree/book/02-Python/Workbooks/10.5-Lists-Loops-Part1-WORKBOOK.ipynb) for this chapter in the cloud.*

In this lesson, we're going to learn more about lists and loops by drawing on DH scholar Anelise Shrout's [Bellevue Almshouse Dataset](https://www.nyuirish.net/almshouse/the-almshouse-records/).

**Preview The Bellevue Almshouse Dataset**

In [ ]:
import pandas
pandas.read_csv("../data/bellevue_almshouse_modified.csv").head(20)

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo
5,1847-04-14,Bridget,Hart,20.0,recent emigrant,spinster,w,Child
6,1847-04-14,Mary,Green,40.0,recent emigrant,spinster,w,And child 2 months
7,1847-04-19,Daniel,Loftus,27.0,destitution,laborer,m,NaN
8,1847-04-10,James,Day,35.0,recent emigrant,laborer,m,NaN
9,1847-04-10,Margaret,Farrell,30.0,recent emigrant,widow,w,NaN
10,1847-04-10,Bridget,Day,30.0,recent emigrant,married,w,NaN
11,1847-04-10,Anthony,Day,0.5,recent emigrant,NaN,m,NaN
12,1847-04-07,James,Collins,22.0,recent emigrant,laborer,m,NaN
13,1847-04-07,Thomas,Collins,21.0,recent emigrant,laborer,m,NaN
14,1847-04-07,Pat,Whalen,25.0,recent emigrant,laborer,m,NaN
15,1847-04-17,Dan,Delany,10.0,typhus,NaN,m,NaN
16,1847-04-09,Catherine,O'Harra,23.0,recent emigrant,married,w,NaN
17,1847-04-09,Damiel,O'Harra,25.0,recent emigrant,laborer,m,NaN
18,1847-04-12,Margaret,Delaney,26.0,recent emigrant,married,w,NaN
19,1847-04-12,Michael,Delany,3.0,recent emigrant,NaN,m,NaN

```{margin} The Bellevue Almshouse Dataset 
The Bellevue Almshouse Dataset includes information about Irish-born immigrants who were admitted to the almshouse in the 1840s. The Bellevue Almshouse was part of New York City's public health system, a place where poor, sick, homeless, and otherwise marginalized people were sent — sometimes voluntarily and sometimes forcibly. This dataset was transcribed from the almshouse's own admissions records by Anelise Shrout.
```

We're using the Bellevue Almshouse Dataset to practice Python lists and loops because we want to think deeply about the consequences of reducing human life to data even at this early stage in our Python journey. This immigration data, as Shrout argues in her essay ["(Re)Humanizing Data: Digitally Navigating the Bellevue Almshouse,"](https://crdh.rrchnm.org/essays/v01-10-(re)-humanizing-data/) was "produced with the express purpose of reducing people to bodies; bodies to easily quantifiable aspects; and assigning value to those aspects which proved that the marginalized people to who they belonged were worth less than their elite counterparts."

As we work through the lesson below, reflect about the categories that these Irish immigrants were slotted into by the NYC government. What should we make of the fact that Python, as a programming language, doesn't understand the meaning or historical context of this data? How can we nevertheless use Python to better understand this history and to interrogate power?

---

In the previous lesson, we learned how to make, manipulate, and iterate through lists, an important Python collection type. In this lesson, we're going to keep practicing and learn how to:

- build lists with `for` loops
- create a running index of items in a list with `enumerate()`
- create one-line `for` loops with *list comprehensions*
- zip lists together with`zip()`
- easily count items in a list

These tools can help us:

- identify how many times a certain value appears in the data (e.g., the so-called disease "recent emigrant")
- programatically change all blank values in the data (e.g., from a blank to "no disease recorded")
- find the most and least common values in the data (e.g., most common "diseases" or professions)

**Example Lists**

Here are the four lists with sample data from the Bellevue Almshouse dataset. Each item in each list corresponds to a single row from the dataset. You might imagine how the code in this lesson might apply to the entire dataset or to other large datasets.

In [ ]:
first_names = ['Unity', 'Catherine', 'Thomas', 'William', 'Patrick', 'Mary Anne', 'Morris',
               'Michael', 'Ellen', 'James', 'Michael', 'Hannah', 'Alexander', 'Mary A', 'Serena?',
               'Margaret', 'Michael', 'Jane', 'Rosanna', 'James', 'Michael', 'John', 'John', 'Mary',
               'Bantel', 'Marcella', 'Arthur', 'Michael', 'Mary', 'Martin']

In [ ]:
last_names =  ['Harkin', 'Doyle', 'McDonald', 'Jordan', 'Rouse', 'Keene', 'Brown',
               'McLoughlin', 'Cassidy', 'Whittle', 'Coyle', 'Cullen', 'Cozens', 
               'Maly', 'McGuire', 'Laly', 'Bahan', 'Combs', 'McGovern', 'Gallagher', 
               'Crone', 'Brannon', 'McDonal', 'Atkins', 'Garragan', 'Wood', 'Kelly', 'Galeny', 'Welch', 'Kerly']

In [ ]:
diseases = ['', 'recent emigrant', 'sickness', '', '', '', 'destitution', '', 'sickness', '',
            'sickness', 'recent emigrant', '', 'insane', 'recent emigrant', 'insane', '', '',
            'sickness', 'sickness', '', 'syphilis', 'sickness', '', 'recent emigrant', 'destitution',
            'sickness', 'recent emigrant', 'sickness', 'sickness']

In [ ]:
ages = ['22', '21', '23', '47', '45', '28', '23', '50', '26', '28', '30', '30', '65', '17', '35',
        '27', '32', '40', '22', '30', '27', '40', '41', '37', '16', '20', '30', '30', '35', '9']

## For Loop

As a refresher, we can use a `for` loop to iterate through a list and do something to each item in the list.

In [ ]:
diseases = ['', 'recent emigrant', 'sickness', '', '', '', 'destitution', '', 'sickness', '',
            'sickness', 'recent emigrant', '', 'insane', 'recent emigrant', 'insane', '', '',
            'sickness', 'sickness', '', 'syphilis', 'sickness', '', 'recent emigrant', 'destitution',
            'sickness', 'recent emigrant', 'sickness', 'sickness']

Below we are iterating through the list `diseases` and printing out every item in the list.

In [ ]:
for disease in diseases:
    print(disease)

recent emigrant
sickness



destitution

sickness

sickness
recent emigrant

insane
recent emigrant
insane


sickness
sickness

syphilis
sickness

recent emigrant
destitution
sickness
recent emigrant
sickness
sickness

Remember that the variable name that will represent each item in the list doesn't exist yet, and it can be named anything you want. Instead of `disease`, we could name the variable `x`

In [ ]:
for x in diseases:
    print(x)

recent emigrant
sickness



destitution

sickness

sickness
recent emigrant

insane
recent emigrant
insane


sickness
sickness

syphilis
sickness

recent emigrant
destitution
sickness
recent emigrant
sickness
sickness

As we've discussed before, however, it's preferable to name your variables something clear that has human language significance.

## Enumerate()

In [ ]:
diseases = ['', 'recent emigrant', 'sickness', '', '', '', 'destitution', '', 'sickness', '',
            'sickness', 'recent emigrant', '', 'insane', 'recent emigrant', 'insane', '', '',
            'sickness', 'sickness', '', 'syphilis', 'sickness', '', 'recent emigrant', 'destitution',
            'sickness', 'recent emigrant', 'sickness', 'sickness']

You might want to keep a numerical count or index of items in a list. To print out each item in the list with a corresponding number, you can use the built-in Python function `enumerate()`.

To access the number that corresponds to each item, you need to unpack *two* variables instead of just one: `number` , `disease`

In [ ]:
for number, disease in enumerate(diseases):
    print(number, disease)

0
1 recent emigrant
2 sickness
3
4
5
6 destitution
7
8 sickness
9
10 sickness
11 recent emigrant
12
13 insane
14 recent emigrant
15 insane
16
17
18 sickness
19 sickness
20
21 syphilis
22 sickness
23
24 recent emigrant
25 destitution
26 sickness
27 recent emigrant
28 sickness
29 sickness

In [ ]:
for number, disease in enumerate(diseases):
    print(f"Person {number}: {disease}")

Person 0:
Person 1: recent emigrant
Person 2: sickness
Person 3:
Person 4:
Person 5:
Person 6: destitution
Person 7:
Person 8: sickness
Person 9:
Person 10: sickness
Person 11: recent emigrant
Person 12:
Person 13: insane
Person 14: recent emigrant
Person 15: insane
Person 16:
Person 17:
Person 18: sickness
Person 19: sickness
Person 20:
Person 21: syphilis
Person 22: sickness
Person 23:
Person 24: recent emigrant
Person 25: destitution
Person 26: sickness
Person 27: recent emigrant
Person 28: sickness
Person 29: sickness

## Build a List with a `For` Loop

We can also make lists with `for` loops. Let's say we wanted to take this list `collection` and create a new list that only contains the items in the list that match `"item we want"`.

In [ ]:
collection = ['item', 'item we want', 'item', 'item', 'item we want']

To do so, we could make an empty list by assigning `empty_list` the value of `[]`—that is, a list with nothing inside of it.  
Then, we could use a `for` loop to iterate through `collection`. If an item equals `"item we want"`, then we will `.append()` that item to our previously empty list.

In [ ]:
empty_list = []
for item in collection:
    if item == "item we want":
        empty_list.append(item)

Check it out!

In [ ]:
empty_list

['item we want', 'item we want']

To iterate through the list `diseases` and make a new list with only the items that match `"recent emigrant"`, we could use the same template.

In [ ]:
diseases = ['', 'recent emigrant', 'sickness', '', '', '', 'destitution', '', 'sickness', '',
            'sickness', 'recent emigrant', '', 'insane', 'recent emigrant', 'insane', '', '',
            'sickness', 'sickness', '', 'syphilis', 'sickness', '', 'recent emigrant', 'destitution',
            'sickness', 'recent emigrant', 'sickness', 'sickness']

In [ ]:
recent_emigrants = []
for disease in diseases:
    if disease == 'recent emigrant':
        recent_emigrants.append(disease)

In [ ]:
recent_emigrants

['recent emigrant',
 'recent emigrant',
 'recent emigrant',
 'recent emigrant',
 'recent emigrant']

How many items are in this list? Remember that we can use the `len()` function to see how many items are in a list.

In [ ]:
len(recent_emigrants)

5

We could also create a new list that revises the old list and transforms blank values into more informative values.

Below we are iterating through the list `diseases`. If an item is blank, then we are adding`"no disease recorded"` to a new `updated_diseases` list. If an item is not blank, we are simply adding the `disease` to the new list.

In [ ]:
updated_diseases = []
for disease in diseases:
    if disease == '':
        new_disease = 'no disease recorded'
        updated_diseases.append(new_disease)
    else:
        updated_diseases.append(disease)

In [ ]:
updated_diseases

['no disease recorded',
 'recent emigrant',
 'sickness',
 'no disease recorded',
 'no disease recorded',
 'no disease recorded',
 'destitution',
 'no disease recorded',
 'sickness',
 'no disease recorded',
 'sickness',
 'recent emigrant',
 'no disease recorded',
 'insane',
 'recent emigrant',
 'insane',
 'no disease recorded',
 'no disease recorded',
 'sickness',
 'sickness',
 'no disease recorded',
 'syphilis',
 'sickness',
 'no disease recorded',
 'recent emigrant',
 'destitution',
 'sickness',
 'recent emigrant',
 'sickness',
 'sickness']

## Zip Lists Together

We can also iterate through multiple lists at the same time by using the `zip()` function, which basically "zips" the lists together.

In [ ]:
first_names = ['Unity', 'Catherine', 'Thomas', 'William', 'Patrick', 'Mary Anne', 'Morris',
               'Michael', 'Ellen', 'James', 'Michael', 'Hannah', 'Alexander', 'Mary A', 'Serena?',
               'Margaret', 'Michael', 'Jane', 'Rosanna', 'James', 'Michael', 'John', 'John', 'Mary',
               'Bantel', 'Marcella', 'Arthur', 'Michael', 'Mary', 'Martin']

In [ ]:
last_names =  ['Harkin', 'Doyle', 'McDonald', 'Jordan', 'Rouse', 'Keene', 'Brown',
               'McLoughlin', 'Cassidy', 'Whittle', 'Coyle', 'Cullen', 'Cozens', 
               'Maly', 'McGuire', 'Laly', 'Bahan', 'Combs', 'McGovern', 'Gallagher', 
               'Crone', 'Brannon', 'McDonal', 'Atkins', 'Garragan', 'Wood', 'Kelly', 'Galeny', 'Welch', 'Kerly']

In [ ]:
updated_diseases

['no disease recorded',
 'recent emigrant',
 'sickness',
 'no disease recorded',
 'no disease recorded',
 'no disease recorded',
 'destitution',
 'no disease recorded',
 'sickness',
 'no disease recorded',
 'sickness',
 'recent emigrant',
 'no disease recorded',
 'insane',
 'recent emigrant',
 'insane',
 'no disease recorded',
 'no disease recorded',
 'sickness',
 'sickness',
 'no disease recorded',
 'syphilis',
 'sickness',
 'no disease recorded',
 'recent emigrant',
 'destitution',
 'sickness',
 'recent emigrant',
 'sickness',
 'sickness']

In [ ]:
ages = ['22', '21', '23', '47', '45', '28', '23', '50', '26', '28', '30', '30', '65', '17', '35',
        '27', '32', '40', '22', '30', '27', '40', '41', '37', '16', '20', '30', '30', '35', '9']

For example, if we wanted to print out each Bellevue Almshouse patient's first name and their "disease" as recorded by the NYC government, we could `zip()` the lists together and unpack multiple variables.

In [ ]:
for first_name, disease in zip(first_names, updated_diseases):
    print(f"{first_name} // {disease}")

Unity // no disease recorded
Catherine // recent emigrant
Thomas // sickness
William // no disease recorded
Patrick // no disease recorded
Mary Anne // no disease recorded
Morris // destitution
Michael // no disease recorded
Ellen // sickness
James // no disease recorded
Michael // sickness
Hannah // recent emigrant
Alexander // no disease recorded
Mary A // insane
Serena? // recent emigrant
Margaret // insane
Michael // no disease recorded
Jane // no disease recorded
Rosanna // sickness
James // sickness
Michael // no disease recorded
John // syphilis
John // sickness
Mary // no disease recorded
Bantel // recent emigrant
Marcella // destitution
Arthur // sickness
Michael // recent emigrant
Mary // sickness
Martin // sickness

In [ ]:
for first_name, last_name, age, disease in zip(first_names, last_names, ages, updated_diseases):
    print(f"{first_name} {last_name} // Age {age} // {disease}")

Unity Harkin // Age 22 // no disease recorded
Catherine Doyle // Age 21 // recent emigrant
Thomas McDonald // Age 23 // sickness
William Jordan // Age 47 // no disease recorded
Patrick Rouse // Age 45 // no disease recorded
Mary Anne Keene // Age 28 // no disease recorded
Morris Brown // Age 23 // destitution
Michael McLoughlin // Age 50 // no disease recorded
Ellen Cassidy // Age 26 // sickness
James Whittle // Age 28 // no disease recorded
Michael Coyle // Age 30 // sickness
Hannah Cullen // Age 30 // recent emigrant
Alexander Cozens // Age 65 // no disease recorded
Mary A Maly // Age 17 // insane
Serena? McGuire // Age 35 // recent emigrant
Margaret Laly // Age 27 // insane
Michael Bahan // Age 32 // no disease recorded
Jane Combs // Age 40 // no disease recorded
Rosanna McGovern // Age 22 // sickness
James Gallagher // Age 30 // sickness
Michael Crone // Age 27 // no disease recorded
John Brannon // Age 40 // syphilis
John McDonal // Age 41 // sickness
Mary Atkins // Age 37 // no disease recorded
Bantel Garragan // Age 16 // recent emigrant
Marcella Wood // Age 20 // destitution
Arthur Kelly // Age 30 // sickness
Michael Galeny // Age 30 // recent emigrant
Mary Welch // Age 35 // sickness
Martin Kerly // Age 9 // sickness

If you try to `zip()` a list that is a different length than the other lists, it will only zip to the length of the shortest list.

In [ ]:
another_list = ['laborer']

In [ ]:
for first_name, last_name, age, disease, list_item in zip(first_names, last_names, ages, updated_diseases, another_list):
    print(f"{first_name} {last_name} // Age {age} // {disease} // {list_item}")

Unity Harkin // Age 22 // no disease recorded // laborer

## Count Items In a List or Collection

If you want to count the items in a list or a collection, you can use the `Counter` module from the `collections` library.

To use this tool, you first need to `import` it. The `import` statement is used whenever you want to import an external Python package or library that was written by someone else.

The `from` keyword allows us to `import` a specific module from a larger library — in this case, from `collections`.

In [ ]:
from collections import Counter

Now that we have `Counter` imported, we can use it. To count the items in a collection, we simply need to insert a collection inside the `Counter()` function.

In [ ]:
Counter(updated_diseases)

Counter({'no disease recorded': 11,
         'recent emigrant': 5,
         'sickness': 9,
         'destitution': 2,
         'insane': 2,
         'syphilis': 1})

This gives us another kind of a collection called a *dictionary*, which we will discuss in a later lesson. This dictionary includes every item in the list and how many times it appears in the list.

#### Most Common

 To sort this Counter dictionary based on the most commonly occurring items, we can use the `.most_common()` method.

In [ ]:
disease_tally = Counter(updated_diseases)
disease_tally.most_common()

[('no disease recorded', 11),
 ('sickness', 9),
 ('recent emigrant', 5),
 ('destitution', 2),
 ('insane', 2),
 ('syphilis', 1)]

We can also select a certain number of the top most common items by placing a number inside the `.most_common()` method.

In [ ]:
disease_tally.most_common(2)

[('no disease recorded', 11), ('sickness', 9)]

#### Least Common

We can also select a certain number of the *least* common items by extracting a slice from the end of list.

In [ ]:
disease_tally.most_common()[-2:]

[('insane', 2), ('syphilis', 1)]

```{admonition}
:class: pythonreview
For a refresher on how to slice from the end of a list, see list slices in the previous lesson.
```

## Exercises

In [ ]:
shuffled_professions = ['married', 'married', 'laborer', 'laborer', 'widow', 'married', 'spinster',
                     'laborer', 'spinster', 'laborer', 'spinster', 'spinster', 'married', 'laborer',
                     'laborer', 'spinster', 'laborer', 'laborer', 'laborer', 'laborer', 'laborer', 'spinster',
                     'laborer', 'spinster', 'widow', 'spinster', 'painter', 'laborer', 'weaver', 'laborer']

### Exercise 1

Make a new list that includes only the items in the list `shuffled_professions` that matches `spinster`

In [ ]:
#Your code here
#Your code here
    #Your code here
        #Your code here

### Exercise 2

Print out each item in the list `shuffled_professions` next to an index number

In [ ]:
#Your code here
    #Your code here

### Exercise 3

Find the most and least common professions in the list `shuffled_professions`

In [ ]:
#Your code here

# 4. Dictionaries

*Note: You can explore the [associated workbook](https://mybinder.org/v2/gh/melaniewalsh/Intro-Cultural-Analytics/master?urlpath=lab/tree/book/02-Python/Workbooks/11.5-Dictionaries-WORKBOOK.ipynb) for this chapter in the cloud.*

In this lesson, we're going to learn about Python dictionaries by drawing on Anelise Shrout's [Bellevue Almshouse Dataset](https://web.archive.org/web/20191220162702/http://www.nyuirish.net/almshouse/the-almshouse-records/), excerpted below.

**Preview The Bellevue Almshouse Dataset**

In [2]:
import pandas
pandas.read_csv("../data/bellevue_almshouse_modified.csv").head(20)

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo
5,1847-04-14,Bridget,Hart,20.0,recent emigrant,spinster,w,Child
6,1847-04-14,Mary,Green,40.0,recent emigrant,spinster,w,And child 2 months
7,1847-04-19,Daniel,Loftus,27.0,destitution,laborer,m,NaN
8,1847-04-10,James,Day,35.0,recent emigrant,laborer,m,NaN
9,1847-04-10,Margaret,Farrell,30.0,recent emigrant,widow,w,NaN
10,1847-04-10,Bridget,Day,30.0,recent emigrant,married,w,NaN
11,1847-04-10,Anthony,Day,0.5,recent emigrant,NaN,m,NaN
12,1847-04-07,James,Collins,22.0,recent emigrant,laborer,m,NaN
13,1847-04-07,Thomas,Collins,21.0,recent emigrant,laborer,m,NaN
14,1847-04-07,Pat,Whalen,25.0,recent emigrant,laborer,m,NaN
15,1847-04-17,Dan,Delany,10.0,typhus,NaN,m,NaN
16,1847-04-09,Catherine,O'Harra,23.0,recent emigrant,married,w,NaN
17,1847-04-09,Damiel,O'Harra,25.0,recent emigrant,laborer,m,NaN
18,1847-04-12,Margaret,Delaney,26.0,recent emigrant,married,w,NaN
19,1847-04-12,Michael,Delany,3.0,recent emigrant,NaN,m,NaN

```{margin} The Bellevue Almshouse Dataset 
The Bellevue Almshouse Dataset includes information about Irish-born immigrants who were admitted to the almshouse in the 1840s. The Bellevue Almshouse was part of New York City's public health system, a place where poor, sick, homeless, and otherwise marginalized people were sent — sometimes voluntarily and sometimes forcibly. This dataset was transcribed from the almshouse's own admissions records by Anelise Shrout.
```

We're using the [Bellevue Almshouse Dataset](https://web.archive.org/web/20191220162702/http://www.nyuirish.net/almshouse/the-almshouse-records/) to practice dictionaries because we want to think deeply about the consequences of reducing human life to data even at this early stage in our Python journey. This immigration data, as Shrout argues in her essay ["(Re)Humanizing Data: Digitally Navigating the Bellevue Almshouse,"](https://crdh.rrchnm.org/essays/v01-10-(re)-humanizing-data/) was "produced with the express purpose of reducing people to bodies; bodies to easily quantifiable aspects; and assigning value to those aspects which proved that the marginalized people to who they belonged were worth less than their elite counterparts."

___

## Dictionary

When we used lists with the Bellevue Almshouse data, it was easier than individually assigning individual variables. We could put multiple names into a single list and multiple ages in a single list.

By using a Python data collection type called a *dictionary*, we can go even further and group each person's name, age, and profession into a single collection.

**Indivudal Variables**

In [ ]:
person1_name = 'Mary Gallagher'
person2_name = 'John Sanin (?)'
person1_age = 18
person2_age = 19

**Lists**

In [ ]:
names = ['Mary Gallagher', 'John Sanin(?)', 'Anthony Clark', 'Margaret Farrell']
ages = [28, 19, 60, 30]
professions = ['married', 'laborer', 'laborer', 'widow']

**Dictionary**

In [ ]:
person1 = {"name": "Mary Gallagher",
             "age": 28,
             "profession": "married"}

In [ ]:
type(person1)

dict

In [ ]:
person2 = {"name": "John Sanin(?)",
             "age": 19,
             "profession": "laborer"}

## Key-Value

A dictionary is made up of "key"-"value" pairs, which are separated by a colon `:` and separated from other key-value pairs by a comma `,`. A dictionary is always enclosed by curly brackets `{}`.

In [ ]:
person1 = {"name": "Mary Gallagher",
             "age": 28,
             "profession": "married"}

You can check all the keys in a dictionary by using the `.keys()` method or all the values in a dictionary by using the `.values()` method.

In [ ]:
person1.keys()

dict_keys(['name', 'age', 'profession'])

In [ ]:
person1.values()

dict_values(['Mary Gallagher', 28, 'married'])

## Access Items

You can access a value in a dictionary by using square brackets `[]` and its key name (kind of like how we indexed a string or a list).

In [ ]:
person1["name"]

'Mary Gallagher'

In [ ]:
person1["age"]

28

In [ ]:
person1["profession"]

'married'

## Change Item

You can change a value in a dictionary by re-assigning a new value to a dictionary key.

In [ ]:
person1["age"] = 100

In [ ]:
person1

{'name': 'Mary Gallagher', 'age': 100, 'profession': 'married'}

In [ ]:
person1['profession'] = 'spinster'

In [ ]:
person1

{'name': 'Mary Gallagher', 'age': 100, 'profession': 'spinster'}

## Nested Dictionary

You can also nest a dictionary inside another dictionary.

In [ ]:
bellevue_people = {
                "person1":
                  {"name": "Mary Gallagher",
                   "age": 28,
                   "profession": "married"},
                "person2":
                  {"name": "John Sanin(?)",
                   "age": 19,
                   "profession": "laborer"}
                }

In [ ]:
bellevue_people['person1']

{'name': 'Mary Gallagher', 'age': 28, 'profession': 'married'}

In [ ]:
bellevue_people['person1']['name']

'Mary Gallagher'

In [ ]:
bellevue_people['person2']

{'name': 'John Sanin(?)', 'age': 19, 'profession': 'laborer'}

In [ ]:
bellevue_people['person2']['age']

19

## Iterate Through Dictionary

In [ ]:
for person in bellevue_people.keys():
    print(person)

person_1
person_2

In [ ]:
for person in bellevue_people.values():
    print(person)

{'name': 'Mary Gallagher', 'age': 28, 'profession': 'married'}
{'name': 'John Sanin(?)', 'age': 19, 'profession': 'laborer'}

In [ ]:
for person in bellevue_people.values():
    if person['age'] > 20:
        name = person['name']
        age = person['age']
        print(f'{name} is more than 20 years old. She is {age}.')

Mary Gallagher is more than 20 years old. She is 28.

In [ ]:
for person in bellevue_people.items():
    print(person)

('person_1', {'name': 'Mary Gallagher', 'age': 28, 'profession': 'married'})
('person_2', {'name': 'John Sanin(?)', 'age': 19, 'profession': 'laborer'})